import os
import shutil
import time
from pathlib import Path
import tkinter.messagebox
from gui import VideoHookApp
from test_clipper import generate_sample_video
from clipper import get_ffmpeg_path

# Prevent modal blocking during headless testing
tkinter.messagebox.showinfo = lambda *args, **kwargs: None
tkinter.messagebox.showwarning = lambda *args, **kwargs: None

def test_gui_initialization():
    print("Testing GUI initialization...")
    app = VideoHookApp()
    app.update()
    print("GUI window initialized and updated successfully!")
    app.destroy()

def test_batch_worker_headless():
    print("\nTesting Batch Worker logic...")
    ffmpeg_bin = get_ffmpeg_path()
    sample_file = "test_episode_batch.mp4"
    generate_sample_video(sample_file, ffmpeg_bin, duration=25.0)

    app = VideoHookApp()
    app.update()

    # Add sample to queue
    app._add_file_to_queue(str(Path(sample_file).resolve()))
    app._refresh_queue_display()
    assert len(app.files_queue) == 1, "Failed to queue test file"

    # Configure short test settings
    app.duration_slider.set(3)
    app.top_k_spin.delete(0, "end")
    app.top_k_spin.insert(0, "2")
    app.skip_entry.delete(0, "end")
    app.skip_entry.insert(0, "2")
    out_dir = Path("test_output_batch")
    app.out_dir_entry.delete(0, "end")
    app.out_dir_entry.insert(0, str(out_dir))

    # Run worker directly (synchronously for test)
    print("Executing worker logic on queued episode...")
    app._batch_worker_thread()
    app.update()

    # Verify generated clips
    clips = list(out_dir.glob("*.mp4"))
    print(f"Generated clips in {out_dir}: {[c.name for c in clips]}")
    assert len(clips) >= 1, "No clips were generated by worker!"

    app.destroy()

    # Cleanup test files
    Path(sample_file).unlink(missing_ok=True)
    shutil.rmtree(out_dir, ignore_errors=True)
    print("Batch test passed and cleaned up successfully!")

if __name__ == "__main__":
    test_batch_worker_headless()
    test_gui_initialization()
